//EXERCISE 2
/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/
#include <iostream>
using namespace std;
 main(){
   int s=2;
    int *arr=new int[s];
    char stop;
    arr[0]=1;
    arr[1]=2;
    int i=0;
    while(arr[i]<4000000){
        arr[i+2]=arr[i]+arr[i+1];
        s++;
        i++;
    }
    s-=2;
    int sum=0;
    for(i=0;i<s;i++)
        if(arr[i]%2==0)
            sum+=arr[i];
    cout<< sum;
    cin>>stop;

}
